name: takeout_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-41.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  csv: ^6.0.0
  excel: ^4.0.6
  path_provider: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
